repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: static/js/.*js
      - id: check-added-large-files
      # - id: check-executables-have-shebangs
      - id: check-json
        exclude: .vscode
      - id: check-toml
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: mixed-line-ending
      - id: double-quote-string-fixer
        exclude: .vscode
      - id: pretty-format-json
        exclude: .vscode
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
