repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    # -   id: check-executables-have-shebangs
    -   id: check-json
        exclude: .vscode
    # -   id: trailing-whitespace
    #     exclude: '\*.md'
# -   repo: https://github.com/pre-commit/mirrors-eslint
#     rev: v8.40.0
#     hooks:
#     -   id: eslint
