# The URL the site will be built for
base_url = "https://henrikgerdes.me"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
# Theme
#theme = "particle-zola"
#theme = "shadharon"
# theme = "hegerdes"

[markdown]
# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "agola-dark"
# The default language; used in feeds.
default_language = "en"

[extra]
# Put all your custom variables here
username = "Henrik Gerdes"
user_description = "Hello"
user_title = "Software Developer"
email = "hegerdes@outlook.de"
github_username = "hegerdes"
gitlab_username = "hegerdes"
linkedin_profile = "https://www.linkedin.com/in/henrik-gerdes-97603b22a/"
mastodon_profile = "https://social.henrikgerdes.me/@hegerdes"
