name: Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docker-build:
    uses: hegerdes/helper-suite/.github/workflows/reusable-docker-build.yml@main
    with:
      build-name: ghcr.io/${{ github.repository_owner }}/homepage
      build-tags: latest
      build-cache: type=gha
      build-args: |
        COMMIT_HASH=${{ github.sha }}
        COMMIT_TAG=${{ github.ref_name }}
      build-labels: MAINTAINER=${{ github.repository_owner }}
      build-platforms: linux/amd64,linux/arm64

  site-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build site
        run: bash zola-build.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # Deployment job
  site-deploy-gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: site-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
