name: Lint and Test build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install dependencies 👨🏻‍💻
        run: bash zola-install.sh

      - name: Run linter 👀
        run: zola check

      - name: Run Build 🛠️
        run: zola build
